project_name: gobootme

before:
  hooks:
  - go generate ./...
builds:
  - id: gobootme
    env:
    - CGO_ENABLED=0
    goos:
    - linux
    goarch:
    - arm64
    - amd64
    binary: gobootme
    main: ./cmd/gobootme

kos:
- repository: ghcr.io/xvzf/gobootme
  main: ./cmd/gobootme
  platforms:
  - linux/amd64
  - linux/arm64
  bare: true
  tags:
  - latest
  - '{{.Tag}}'
  - '{{if not .Prerelease}}stable{{end}}'
